info:
  version: v1.35.0
  title: data_source_huaweicloud_gaussdb_mysql_configuration
  description: 
schemes:
  - https
host: huaweicloud.com
tags:
  - name: gaussdb
paths:
  /mysql/v3/{project_id}/configurations:
    get:
      tag: gaussdb
      operationId: List
