info:
  version: v1.35.0
  title: resource_huaweicloud_apig_environment
  description: 
schemes:
  - https
host: huaweicloud.com
tags:
  - name: apig
paths:
  /v2/{project_id}/apigw/instances/{instanceId}/{path}/{id}:
    delete:
      tag: apig
      operationId: Delete
    put:
      tag: apig
      operationId: Update
  /v2/{project_id}/apigw/instances/{instanceId}/{path}:
    get:
      tag: apig
      operationId: List
    post:
      tag: apig
      operationId: Create
